apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: devopsfaith/krakend:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
---
apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  selector:
    app: krakend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
